'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

Example 2:
    Input: s = "", t = "y"
    Output: "y"
'''
def findTheDifference( s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    # set arr of t
    t_list = list(t)
    # Iterate string s
    for i in s:
        # remove iterated value from t_list
        t_list.remove(i)
        
    return t_list[0]